modLoader="javafml"
loaderVersion="[47,)"
license="Academic Free License v3.0"

[[mods]]
modId="oclotium"
version="1.0.0"
displayName="oclotium"
displayURL="https://mcreator.net"
credits="Created using mod maker MCreator - https://mcreator.net/about"
authors="ocelo, MCreator"
description="random stuff :>"

[[dependencies.oclotium]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="NONE"
    side="BOTH"



[[dependencies.oclotium]]
    modId="curios_api"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.oclotium]]
    modId="geckolib"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.oclotium]]
    modId="jsonforhttprequest"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"

