modLoader="javafml"
loaderVersion="[47,)"
license="Academic Free License v3.0"

[[mods]]
modId="niewiem"
version="1.0.0"
displayName="niewiem"
displayURL="https://mcreator.net"
credits="Created using mod maker MCreator - https://mcreator.net/about"
authors="Krupnik, Ocelot, MCreator"
description="random stuff :>"

[[dependencies.niewiem]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="NONE"
    side="BOTH"



[[dependencies.niewiem]]
    modId="curios_api"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.niewiem]]
    modId="geckolib"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.niewiem]]
    modId="jsonforhttprequest"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"

